# Generated by Django 4.2.4 on 2023-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_price_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Descriptions',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
