# Generated by Django 4.2.4 on 2023-08-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_campaigns_product_saleprice_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SalePrice',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.campaigns'),
        ),
    ]
