# Generated by Django 4.2.4 on 2023-08-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_product_category_alter_product_saleprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isSale',
        ),
        migrations.AlterField(
            model_name='product',
            name='SalePrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
