# Generated by Django 4.2.4 on 2023-08-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_descriptions_alter_campaigns_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
